version: '3.3'
services:
  importer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amp-importer
    volumes:
      - .:/app
    command: python data_importer.py
    networks:
      - backend
      - default


networks:
  default: null
  backend:
    external:
      name: backend
