version: '3.3'
services:
  importer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amp-importer
    volumes:
      - .:/app
    command: python data_importer.py
    networks:
      - pr-4394_rwanda_default
networks:
  pr-4394_rwanda_default:
    driver: bridge

