---
version: "3.3"
services:
  airflow-common:
    image: ${AIRFLOW_IMAGE}
    env_file:
      - .env
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
      - /opt/etl:/opt/etl:ro
    user: ${AIRFLOW_UID:-50000}:0
    command: webserver
    ports:
      - "8080:8080"
    container_name: airlow
    labels:
      - "traefik.frontend.rule=Host:${AIRFLOW_HOST}"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_default"
    networks:
      - default
      - backend
      - nginxproxy

  airflow-scheduler:
    image: ${AIRFLOW_IMAGE}
    env_file:
      - .env
    volumes:
      - ${AIRFLOW_PROJ_DIR:-.}/dags:/opt/airflow/dags
      - ${AIRFLOW_PROJ_DIR:-.}/logs:/opt/airflow/logs
      - ${AIRFLOW_PROJ_DIR:-.}/plugins:/opt/airflow/plugins
      - /opt/etl:/opt/etl:ro
    user: "${AIRFLOW_UID:-50000}:0"
    networks:
      - default
      - backend
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

networks:
  default: null
  nginxproxy:
    external:
      name: traefik_default
  backend:
    external:
      name: backend
